use lmda;

-- \W -- enable warnings if using this script from mysql terminal with "source import-assessments.sql;"
-- the update-join query takes about 2 minutes to run, and the whole script takes maybe 4 or 5.

drop TABLE if exists `assessments`;
CREATE TABLE `assessments` (
    `PARID` VARCHAR(16),
    `PROPERTYHOUSENUM` VARCHAR(5), `PROPERTYFRACTION` VARCHAR(7), `PROPERTYADDRESS` VARCHAR(31), `PROPERTYCITY` VARCHAR(22), `PROPERTYSTATE` VARCHAR(2), `PROPERTYUNIT` VARCHAR(14), `PROPERTYZIP` VARCHAR(5),
    
    `MUNICODE` VARCHAR(3), `MUNIDESC` VARCHAR(23), 
    `SCHOOLCODE` VARCHAR(2), `SCHOOLDESC` VARCHAR(20),
    
    `LEGAL1` VARCHAR(60), `LEGAL2` VARCHAR(60), `LEGAL3` VARCHAR(60), 
    
    `NEIGHCODE` VARCHAR(6), `NEIGHDESC` VARCHAR(39), 
    `TAXCODE` VARCHAR(1), `TAXDESC` VARCHAR(38), 
    `TAXSUBCODE` VARCHAR(1), `TAXSUBCODE_DESC` VARCHAR(15), 
    `OWNERCODE` VARCHAR(2), `OWNERDESC` VARCHAR(24), 
    `CLASS` VARCHAR(1), `CLASSDESC` VARCHAR(12), 
    `USECODE` VARCHAR(4), `USEDESC` VARCHAR(33),

    `LOTAREA` VARCHAR(10), `HOMESTEADFLAG` VARCHAR(3), `CLEANGREEN` VARCHAR(1),
    `FARMSTEADFLAG` VARCHAR(3), `ABATEMENTFLAG` VARCHAR(1), `RECORDDATE` VARCHAR(10),
    `SALEDATE` VARCHAR(10), `SALEPRICE` VARCHAR(9), 
    `SALECODE` VARCHAR(2), `SALEDESC` VARCHAR(25),
    `DEEDBOOK` VARCHAR(8), `DEEDPAGE` VARCHAR(8),
    `PREVSALEDATE` VARCHAR(10), `PREVSALEPRICE` VARCHAR(9), `PREVSALEDATE2` VARCHAR(10), `PREVSALEPRICE2` VARCHAR(8), 

    `CHANGENOTICEADDRESS1` VARCHAR(43), `CHANGENOTICEADDRESS2` VARCHAR(79), `CHANGENOTICEADDRESS3` VARCHAR(31), `CHANGENOTICEADDRESS4` VARCHAR(5),

    `COUNTYBUILDING` VARCHAR(9), `COUNTYLAND` VARCHAR(9), `COUNTYTOTAL` VARCHAR(10), `COUNTYEXEMPTBLDG` VARCHAR(9),

    `LOCALBUILDING` VARCHAR(9), `LOCALLAND` VARCHAR(9), `LOCALTOTAL` VARCHAR(10),
    `FAIRMARKETBUILDING` VARCHAR(9), `FAIRMARKETLAND` VARCHAR(9), `FAIRMARKETTOTAL` VARCHAR(10), 
    `STYLE` VARCHAR(2), `STYLEDESC` VARCHAR(14),
    `STORIES` VARCHAR(3), `YEARBLT` VARCHAR(4),
    `EXTERIORFINISH` VARCHAR(1), `EXTFINISH_DESC` VARCHAR(14),
    `ROOF` VARCHAR(1), `ROOFDESC` VARCHAR(7),
    `BASEMENT` VARCHAR(1), `BASEMENTDESC` VARCHAR(10),
    `GRADE` VARCHAR(3), `GRADEDESC` VARCHAR(15),
    `CONDITION` VARCHAR(1), `CONDITIONDESC` VARCHAR(9),
    `CDU` VARCHAR(2), `CDUDESC` VARCHAR(9), `TOTALROOMS` VARCHAR(2), `BEDROOMS` VARCHAR(2), `FULLBATHS` VARCHAR(2), `HALFBATHS` VARCHAR(1), `HEATINGCOOLING` VARCHAR(1), `HEATINGCOOLINGDESC` VARCHAR(21), `FIREPLACES` VARCHAR(2), `BSMTGARAGE` VARCHAR(1), `FINISHEDLIVINGAREA` VARCHAR(5), `CARDNUMBER` VARCHAR(2), `ALT_ID` VARCHAR(16), `TAXYEAR` VARCHAR(4), `ASOFDATE` VARCHAR(10),

    `MUNICIPALITY` VARCHAR(1), `NEIGHBORHOOD` VARCHAR(1), `PGH_COUNCIL_DISTRICT` VARCHAR(1), `PGH_WARD` VARCHAR(1), `PGH_PUBLIC_WORKS_DIVISION` VARCHAR(1), `PGH_POLICE_ZONE` VARCHAR(1), `PGH_FIRE_ZONE` VARCHAR(1), `TRACT` VARCHAR(1),     `BLOCK_GROUP` VARCHAR(1)
);

load data local infile 'data-wprdc-org_dataset_property-assessments_resource_518b583f-7cc8-4f60-94d0-174cc98310dc.csv' into table assessments fields terminated by ',' ENCLOSED BY '"' ESCAPED BY '' LINES TERMINATED BY '\n' ignore 1 lines;

alter table assessments add column id integer primary key auto_increment first;
select id, PARID, PROPERTYHOUSENUM, PROPERTYFRACTION, PROPERTYADDRESS, PROPERTYCITY, PROPERTYSTATE,
PROPERTYUNIT, PROPERTYZIP, MUNICODE, MUNIDESC, SCHOOLCODE, SCHOOLDESC,
LEGAL1, LEGAL2, LEGAL3, NEIGHCODE, NEIGHDESC, TAXCODE, TAXDESC from assessments where id = 49695;

alter table assessments add unique(PARID);
update assessments set COUNTYTOTAL = null where COUNTYTOTAL = '';
alter table assessments add key(COUNTYTOTAL);
drop table if exists PROPERTYLOCATION;
alter table assessments add key(PROPERTYHOUSENUM, PROPERTYFRACTION, PROPERTYADDRESS, PROPERTYCITY, PROPERTYSTATE, PROPERTYUNIT, PROPERTYZIP);

create table PROPERTYLOCATION select distinct PROPERTYHOUSENUM, PROPERTYFRACTION, PROPERTYADDRESS, PROPERTYCITY, PROPERTYSTATE, PROPERTYUNIT, PROPERTYZIP from assessments;
update PROPERTYLOCATION set PROPERTYHOUSENUM = null where PROPERTYHOUSENUM = '';
update PROPERTYLOCATION set PROPERTYFRACTION = null where PROPERTYFRACTION = '';
update PROPERTYLOCATION set PROPERTYADDRESS  = null where PROPERTYADDRESS  = '';
update PROPERTYLOCATION set PROPERTYCITY     = null where PROPERTYCITY     = '';
update PROPERTYLOCATION set PROPERTYSTATE    = null where PROPERTYSTATE    = '';
update PROPERTYLOCATION set PROPERTYUNIT     = null where PROPERTYUNIT     = '';
update PROPERTYLOCATION set PROPERTYZIP      = null where PROPERTYZIP      = '';


alter table PROPERTYLOCATION add column id integer primary key auto_increment first;

alter table assessments add column PROPERTYLOCATIONID integer after id;
UPDATE assessments a join PROPERTYLOCATION pl on pl.PROPERTYHOUSENUM = a.PROPERTYHOUSENUM and pl.PROPERTYFRACTION = a.PROPERTYFRACTION and pl.PROPERTYADDRESS = a.PROPERTYADDRESS and pl.PROPERTYCITY = a.PROPERTYCITY and pl.PROPERTYSTATE = a.PROPERTYSTATE and pl.PROPERTYUNIT = a.PROPERTYUNIT and pl.PROPERTYZIP = a.PROPERTYZIP set a.PROPERTYLOCATIONID = pl.id;

alter table assessments drop column PROPERTYHOUSENUM, drop column PROPERTYFRACTION, drop column PROPERTYADDRESS, drop column PROPERTYCITY, drop column PROPERTYSTATE, drop column PROPERTYUNIT, drop column PROPERTYZIP;

